create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,date_of_birth date,gender text,interested_in text,location text,bio text check(char_length(bio)<=500),created_at timestamptz default now(),updated_at timestamptz default now());
alter table public.profiles enable row level security;
drop policy if exists "Profiles are publicly viewable" on public.profiles;
create policy "Profiles are publicly viewable" on public.profiles for select using(true);
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id) values(new.id) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table if not exists public.profile_photos(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,storage_path text not null,sort_order integer not null default 0,created_at timestamptz default now());
alter table public.profile_photos enable row level security;
create policy "Photos are viewable" on public.profile_photos for select using(true);
create policy "Users manage own photos" on public.profile_photos for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
