'use client'
import {ChangeEvent,FormEvent,useEffect,useState} from 'react'
import {createClient} from '../../lib/supabase'

type Photo={id:string,storage_path:string,sort_order:number}

export default function Profile(){
 const [uid,setUid]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[msg,setMsg]=useState('')
 const [photos,setPhotos]=useState<Photo[]>([])
 const [f,setF]=useState({display_name:'',date_of_birth:'',gender:'',interested_in:'',location:'',bio:''})
 useEffect(()=>{(async()=>{const c=createClient(),{data:{user}}=await c.auth.getUser();if(!user){window.location.href='/login';return}setUid(user.id);const{data}=await c.from('profiles').select('*').eq('id',user.id).maybeSingle();if(data)setF({display_name:data.display_name||'',date_of_birth:data.date_of_birth||'',gender:data.gender||'',interested_in:data.interested_in||'',location:data.location||'',bio:data.bio||''});await loadPhotos(user.id);setLoading(false)})()},[])
 async function loadPhotos(id:string){const c=createClient();const{data}=await c.from('profile_photos').select('*').eq('user_id',id).order('sort_order');if(data)setPhotos(data)}
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');const age=Math.floor((Date.now()-new Date(f.date_of_birth).getTime())/31557600000);if(age<18){setMsg('You must be 18 or older.');setSaving(false);return}const{error}=await createClient().from('profiles').update({...f,updated_at:new Date().toISOString()}).eq('id',uid);setMsg(error?'Could not save: '+error.message:'Profile saved successfully.');setSaving(false)}
 async function upload(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);if(!files.length)return;if(photos.length+files.length>6){setMsg('You can have a maximum of 6 photos.');return}setUploading(true);setMsg('');const c=createClient();for(const file of files){if(!file.type.startsWith('image/')){setMsg('Only image files are allowed.');break}if(file.size>5*1024*1024){setMsg('Each photo must be 5MB or smaller.');break}const path=`${uid}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error}=await c.storage.from('profile-photos').upload(path,file,{upsert:false});if(error){setMsg('Upload failed: '+error.message);break}const{error:dbError}=await c.from('profile_photos').insert({user_id:uid,storage_path:path,sort_order:photos.length});if(dbError){await c.storage.from('profile-photos').remove([path]);setMsg('Could not save photo record: '+dbError.message);break}await loadPhotos(uid)}setUploading(false);e.target.value=''}
 async function removePhoto(p:Photo){const c=createClient();await c.storage.from('profile-photos').remove([p.storage_path]);await c.from('profile_photos').delete().eq('id',p.id);await loadPhotos(uid)}
 function photoUrl(path:string){return createClient().storage.from('profile-photos').getPublicUrl(path).data.publicUrl}
 if(loading)return <main className="auth"><div className="card">Loading profile...</div></main>
 return <main className="auth"><a className="back" href="/dashboard">← Dashboard</a><form className="card" onSubmit={save}><h1>Your dating profile</h1><p>Complete your profile so people can get to know you.</p>
 <div className="photos"><h3>Profile photos ({photos.length}/6)</h3><div className="photoGrid">{photos.map(p=><div className="photo" key={p.id}><img src={photoUrl(p.storage_path)} alt="Profile photo"/><button type="button" onClick={()=>removePhoto(p)}>Remove</button></div>)}</div>{photos.length<6&&<label className="upload">＋ Add photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={upload} disabled={uploading}/></label>}<small>Use clear photos of yourself. Maximum 6 photos, 5MB each.</small></div>
 <input value={f.display_name} onChange={e=>set('display_name',e.target.value)} placeholder="Display name" required/><label>Date of birth<input type="date" value={f.date_of_birth} onChange={e=>set('date_of_birth',e.target.value)} required/></label><label>Gender<select value={f.gender} onChange={e=>set('gender',e.target.value)} required><option value="">Select</option><option>Man</option><option>Woman</option><option>Non-binary</option><option>Prefer not to say</option></select></label><label>Interested in<select value={f.interested_in} onChange={e=>set('interested_in',e.target.value)} required><option value="">Select</option><option>Men</option><option>Women</option><option>Everyone</option></select></label><input value={f.location} onChange={e=>set('location',e.target.value)} placeholder="City / area"/><textarea value={f.bio} onChange={e=>set('bio',e.target.value)} placeholder="Short bio (max 500 characters)" maxLength={500} rows={5}/><button disabled={saving}>{saving?'Saving...':'Save profile'}</button>{msg&&<div className="notice">{msg}</div>}</form></main>
}
